// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: AGPL-3.0-only

package app.accrescent.server.adapters.driving.api.authn.vertx

import app.accrescent.server.adapters.driven.datastore2.vertx.MemoryDataStore
import app.accrescent.server.adapters.driven.randomsource.DeterministicRandomSource
import app.accrescent.server.adapters.driven.timestampsource.FixedTimestampSource
import app.accrescent.server.core.NonEmptyString
import app.accrescent.server.core.unwrap
import app.accrescent.server.domain.IdGenerator
import app.accrescent.server.domain.api.authn.AuthenticationApiImpl
import app.accrescent.server.domain.config.AuthnConfig
import app.accrescent.server.domain.config.GithubAuthnConfig
import app.accrescent.server.domain.config.SessionConfig
import app.accrescent.server.domain.config.SessionLifetime
import app.accrescent.server.domain.ports.driving.api.authn.AuthenticationApi
import app.accrescent.server.domain.uri.HttpUri
import io.netty.handler.codec.http.HttpResponseStatus
import io.netty.handler.codec.http.QueryStringDecoder
import io.restassured.RestAssured.given
import io.restassured.http.Cookie
import io.restassured.http.Method
import io.restassured.response.Response
import io.vertx.core.Vertx
import io.vertx.core.http.HttpHeaders
import io.vertx.core.http.HttpServer
import io.vertx.core.http.HttpServerRequest
import io.vertx.core.json.JsonObject
import io.vertx.kotlin.coroutines.dispatcher
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertNotNull
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource
import kotlin.io.encoding.Base64

private const val GITHUB_LOGIN_PATH = "/auth/github/login"
private const val GITHUB_CALLBACK_PATH = "/auth/github/callback"
private const val GITHUB_STATE_COOKIE_NAME = "__Host-Http-github-state"
private const val GITHUB_CODE_VERIFIER_COOKIE_NAME = "__Host-Http-github-code-verifier"
private const val SESSION_COOKIE_NAME = "__Host-Http-session"

private const val CLIENT_ID = "test-client-id"
private const val CLIENT_SECRET = "test-client-secret"
private const val LOGIN_COOKIE_MAX_AGE_SECONDS = 600L
private const val REDIRECT_URI = "https://example.com/auth/github/callback"
private const val VALID_STATE = "test-state"
private const val VALID_CODE_VERIFIER = "test-code-verifier"
private const val VALID_CODE = "valid-code"
private const val SESSION_LIFETIME = "1h"
private const val SESSION_LIFETIME_SECONDS = 3600L

class AuthnServerTest {
    @ParameterizedTest
    @ValueSource(strings = [GITHUB_LOGIN_PATH, GITHUB_CALLBACK_PATH])
    fun `responses are not cacheable`(path: String) {
        val response = request(path)

        assertEquals("no-store", response.header(HttpHeaders.CACHE_CONTROL.toString()))
    }

    @ParameterizedTest
    @ValueSource(strings = [GITHUB_LOGIN_PATH, GITHUB_CALLBACK_PATH])
    fun `non-GET request is rejected`(path: String) {
        val response = request(path, method = Method.POST)

        assertEquals(HttpResponseStatus.METHOD_NOT_ALLOWED.code(), response.statusCode)
        assertEquals("GET", response.header(HttpHeaders.ALLOW.toString()))
    }

    @Test
    fun `GitHub login redirects to GitHub authorization with correct URL params and cookies`() {
        val response = request(GITHUB_LOGIN_PATH)
        val location = response.header(HttpHeaders.LOCATION.toString())?.let(::QueryStringDecoder)

        val expectedState = "YLQguzhR2dR6y5M9vnA5mw"
        // Status code
        assertEquals(HttpResponseStatus.FOUND.code(), response.statusCode)
        // Location header
        assertNotNull(location)
        assertEquals("$githubOrigin/login/oauth/authorize", location.path())
        // URL parameters
        assertEquals(
            mapOf(
                "client_id" to CLIENT_ID,
                "redirect_uri" to REDIRECT_URI,
                // state and code_challenge are generated by DeterministicRandomSource
                "state" to expectedState,
                "code_challenge" to "vx_gXmI6Rukxbi2vUqMVw0vkXK0urEDTCKCFjZAzdVM",
                "code_challenge_method" to "S256",
                // Required by https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1
                "response_type" to "code",
            ),
            location.parameters().mapValues { it.value.single() },
        )
        // Cookies
        assertEquals(
            hostHttpCookieBuilder(GITHUB_STATE_COOKIE_NAME, expectedState)
                .setSameSite("Lax")
                .setMaxAge(LOGIN_COOKIE_MAX_AGE_SECONDS)
                .build(),
            response.detailedCookie(GITHUB_STATE_COOKIE_NAME),
        )
        assertEquals(
            // Generated by DeterministicRandomSource
            hostHttpCookieBuilder(
                GITHUB_CODE_VERIFIER_COOKIE_NAME,
                "9sktozrwHU-3cOmMAyX0HT66-JhtpxLIK81NVUvwtUA",
            )
                .setSameSite("Lax")
                .setMaxAge(LOGIN_COOKIE_MAX_AGE_SECONDS)
                .build(),
            response.detailedCookie(GITHUB_CODE_VERIFIER_COOKIE_NAME),
        )
    }

    @Test
    fun `GitHub callback clears login cookies`() {
        val response = request(
            GITHUB_CALLBACK_PATH,
            GITHUB_STATE_COOKIE_NAME to "some-state",
            GITHUB_CODE_VERIFIER_COOKIE_NAME to "some-code-verifier",
        )

        for (name in listOf(GITHUB_STATE_COOKIE_NAME, GITHUB_CODE_VERIFIER_COOKIE_NAME)) {
            assertEquals(
                hostHttpCookieBuilder(name, "")
                    .setSameSite("Lax")
                    .setMaxAge(0)
                    .build(),
                response.detailedCookie(name),
            )
        }
    }

    @Test
    fun `GitHub callback with valid code, state, and code verifier sets session cookie and redirects to correct route`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        // Session cookie
        assertEquals(
            // Generated by DeterministicRandomSource
            hostHttpCookieBuilder(SESSION_COOKIE_NAME, "s_2wTa5P82Lwqd50UvNyQRad")
                .setSameSite("Strict")
                .setMaxAge(SESSION_LIFETIME_SECONDS)
                .build(),
            response.detailedCookie(SESSION_COOKIE_NAME),
        )
        // Redirect
        assertEquals(HttpResponseStatus.FOUND.code(), response.statusCode)
        assertEquals("/", response.header(HttpHeaders.LOCATION.toString()))
    }

    @Test
    fun `GitHub callback without state cookie is rejected as bad request`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE&state=$VALID_STATE",
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback without code verifier cookie is rejected as bad request`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback without state param is rejected`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback without code param is rejected`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback with mismatched state is rejected`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE&state=other-state",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback with access denied error redirects to correct route`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?error=access_denied&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.FOUND.code(), response.statusCode)
        assertEquals("/", response.header(HttpHeaders.LOCATION.toString()))
    }

    @Test
    fun `GitHub callback with error other than access denied is rejected as bad request`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?error=redirect_uri_mismatch&code=$VALID_CODE&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback with code rejected by GitHub fails with bad gateway`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=invalid-code&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to VALID_CODE_VERIFIER,
        )

        assertEquals(HttpResponseStatus.BAD_GATEWAY.code(), response.statusCode)
    }

    @Test
    fun `GitHub callback with wrong code verifier fails with bad gateway`() {
        val response = request(
            "$GITHUB_CALLBACK_PATH?code=$VALID_CODE&state=$VALID_STATE",
            GITHUB_STATE_COOKIE_NAME to VALID_STATE,
            GITHUB_CODE_VERIFIER_COOKIE_NAME to "other-code-verifier",
        )

        assertEquals(HttpResponseStatus.BAD_GATEWAY.code(), response.statusCode)
    }

    @Test
    fun `request for unknown path is not found`() {
        val response = request("/auth/unknown/login")

        assertEquals(HttpResponseStatus.NOT_FOUND.code(), response.statusCode)
    }

    private lateinit var githubServer: HttpServer
    private lateinit var githubOrigin: String
    private lateinit var dataStore: MemoryDataStore
    private lateinit var server: HttpServer

    @BeforeEach
    fun startServers() {
        githubServer = vertx.createHttpServer()
            .requestHandler(::handleGithubRequest)
            .listen(0, "localhost")
            .await()
        githubOrigin = "http://localhost:${githubServer.actualPort()}"

        dataStore = MemoryDataStore(vertx)
        dataStore.migrateToHead().unwrap()
        server = startAuthnServer(
            AuthenticationApiImpl(
                dataStore = dataStore,
                idGenerator = IdGenerator(DeterministicRandomSource()),
                sessionLifetime = SessionLifetime.parse(SESSION_LIFETIME).unwrap(),
                timestampSource = FixedTimestampSource(),
            ),
        )
    }

    /**
     * Starts an HTTP server serving an [AuthnServer] which uses the stub GitHub server.
     *
     * @param authenticationApi the authentication API for the [AuthnServer] to use.
     * @return the started HTTP server.
     */
    private fun startAuthnServer(authenticationApi: AuthenticationApi): HttpServer {
        val authnServer = AuthnServer(
            vertx = vertx,
            context = vertx.dispatcher(),
            authnConfig = AuthnConfig(
                github = GithubAuthnConfig(
                    clientId = NonEmptyString.fromString(CLIENT_ID).unwrap(),
                    clientSecret = NonEmptyString.fromString(CLIENT_SECRET).unwrap(),
                    redirectUri = HttpUri.fromString(REDIRECT_URI).unwrap(),
                ),
                session = SessionConfig(
                    lifetime = SessionLifetime.parse(SESSION_LIFETIME).unwrap(),
                ),
            ),
            authenticationApi = authenticationApi,
            randomSource = DeterministicRandomSource(),
            githubSite = "$githubOrigin/login",
            githubUserInfoPath = "$githubOrigin/user",
        )

        return vertx.createHttpServer()
            .requestHandler(authnServer)
            .listen(0, "localhost")
            .await()
    }

    @AfterEach
    fun stopServers() {
        server.close().await()
        dataStore.close().unwrap()
        githubServer.close().await()
    }

    /**
     * Makes a request to the auth server.
     *
     * @param pathAndQuery the path and query of the request URI.
     * @param cookies the (name, value) pairs of cookies to send.
     * @param method the HTTP method of the request.
     * @return the response.
     */
    private fun request(
        pathAndQuery: String,
        vararg cookies: Pair<String, String>,
        method: Method = Method.GET,
    ): Response {
        return given()
            .redirects().follow(false)
            .cookies(cookies.toMap())
            .request(method, "http://localhost:${server.actualPort()}$pathAndQuery")
    }

    private companion object {
        private val vertx = Vertx.vertx()

        @AfterAll
        @JvmStatic
        fun closeVertx() {
            vertx.close().await()
        }

        private val CLIENT_AUTHORIZATION =
            "Basic ${Base64.encode("$CLIENT_ID:$CLIENT_SECRET".toByteArray())}"

        /**
         * Handles requests to the stub GitHub server.
         *
         * The token endpoint only issues an access token for [VALID_CODE] with [VALID_CODE_VERIFIER],
         * [REDIRECT_URI], and the expected client credentials (sent via HTTP Basic authentication), and the user
         * endpoint only accepts that access token.
         */
        private fun handleGithubRequest(request: HttpServerRequest) {
            val response = request.response().putHeader(HttpHeaders.CONTENT_TYPE, "application/json")

            val fakeAccessToken = "test-access-token"
            val path: String? = request.path()
            when (path) {
                "/login/oauth/access_token" -> request.body().onSuccess { body ->
                    val params = QueryStringDecoder(body.toString(), false)
                        .parameters()
                        .mapValues { it.value.single() }
                    val expectedParams = mapOf(
                        "code" to VALID_CODE,
                        "code_verifier" to VALID_CODE_VERIFIER,
                        "grant_type" to "authorization_code",
                        "redirect_uri" to REDIRECT_URI,
                    )
                    val responseBody = if (
                        request.getHeader(HttpHeaders.AUTHORIZATION) == CLIENT_AUTHORIZATION
                        && params == expectedParams
                    ) {
                        JsonObject().put("access_token", fakeAccessToken).put("token_type", "bearer")
                    } else {
                        JsonObject().put("error", "bad_verification_code")
                    }
                    response.end(responseBody.encode())
                }

                "/user" -> if (request.getHeader(HttpHeaders.AUTHORIZATION) == "Bearer $fakeAccessToken") {
                    // Arbitrary GitHub user ID - just needs to fit into a Long
                    response.end(JsonObject().put("id", 12345).encode())
                } else {
                    response.setStatusCode(HttpResponseStatus.UNAUTHORIZED.code()).end()
                }

                else -> response.setStatusCode(HttpResponseStatus.NOT_FOUND.code()).end()
            }
        }
    }
}

/**
 * Creates a cookie builder with the attributes required by the `__Host-Http-` cookie name
 * prefix.
 *
 * @param name the cookie name.
 * @param value the cookie value.
 * @return a builder with Path set to "/", Secure set, and HttpOnly set.
 */
private fun hostHttpCookieBuilder(name: String, value: String): Cookie.Builder {
    return Cookie.Builder(name, value)
        .setPath("/")
        .setSecured(true)
        .setHttpOnly(true)
}
